# Generated by Django 4.2.16 on 2024-12-04 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(max_length=255)),
                ('requirement', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
