# Generated by Django 4.2.16 on 2024-12-04 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='requirement',
            new_name='requirements',
        ),
    ]
