# Generated by Django 4.2.16 on 2024-12-04 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_requirement_requisition_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(max_length=255)),
                ('signer', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Requisition',
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.report')),
                ('product', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=255)),
                ('document_date', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('buldingType', models.CharField(max_length=255)),
                ('buldingStructure', models.CharField(max_length=255)),
                ('structureID', models.CharField(max_length=255)),
                ('buildingPlace', models.CharField(max_length=255)),
                ('contractID', models.CharField(max_length=255)),
                ('contractDate', models.CharField(max_length=255)),
                ('products', models.CharField(max_length=255)),
                ('departmentCode', models.CharField(max_length=255)),
            ],
            bases=('api.report',),
        ),
    ]
