# Generated by Django 4.2.16 on 2024-12-09 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report_delete_requisition_productreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
