# Generated by Django 4.2.16 on 2024-12-09 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_created_date_report_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='contractDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='document_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
