# Generated by Django 4.2.16 on 2024-12-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_productreport_contractdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.BinaryField()),
            ],
        ),
    ]
