# Generated by Django 4.2.16 on 2024-12-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_documentformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(default='product', max_length=255),
        ),
    ]
