# Generated by Django 4.2.16 on 2024-12-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_report_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreport',
            old_name='buldingStructure',
            new_name='buildingStructure',
        ),
        migrations.RenameField(
            model_name='productreport',
            old_name='buldingType',
            new_name='buildingType',
        ),
        migrations.AlterField(
            model_name='productreport',
            name='contractDate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='document_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='create_date',
            field=models.CharField(max_length=255),
        ),
    ]
