# Generated by Django 4.2.16 on 2024-12-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_buldingstructure_productreport_buildingstructure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.CharField(max_length=50)),
                ('tabs', models.JSONField(default=list)),
                ('indentation', models.JSONField(default=dict)),
                ('spacing', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentformat',
            name='file',
        ),
        migrations.AlterField(
            model_name='documentformat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('underline', models.IntegerField(default=0)),
                ('font', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('color', models.CharField(max_length=7)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='api.paragraph')),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='document_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='api.documentformat'),
        ),
    ]
