# Generated by Django 4.2.16 on 2024-12-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_paragraph_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='bold',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='italic',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='underline',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
