# Generated by Django 4.2.16 on 2024-12-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_text_bold_alter_text_italic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
