# Generated by Django 4.2.16 on 2024-12-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(default=0, null=True)),
                ('left', models.IntegerField(default=0, null=True)),
                ('right', models.IntegerField(default=0, null=True)),
                ('bottom', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
