# Generated by Django 4.2.16 on 2024-12-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='font',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='size',
            field=models.FloatField(null=True),
        ),
    ]
