# Generated by Django 4.2.16 on 2024-12-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_text_font_alter_text_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreport',
            name='table',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
