# Generated by Django 4.2.16 on 2024-12-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0021_customuser_alter_report_create_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='MyUser',
        ),
    ]
