# Generated by Django 4.2.16 on 2025-01-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userdetail_alter_report_create_by_delete_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
