# Generated by Django 4.2.16 on 2025-02-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_documentformat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='priority',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
