# Generated by Django 4.2.16 on 2025-02-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_productreport_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
