# Generated by Django 4.2.16 on 2025-02-27 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_buildingstructure_productreport_buildingstruct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDrawReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.report')),
                ('sDraw', models.CharField(max_length=255)),
                ('sDraws', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255)),
                ('priority', models.CharField(blank=True, max_length=255)),
                ('document_number', models.CharField(max_length=255)),
                ('document_date', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('buildingType', models.CharField(max_length=255)),
                ('buildingStruct', models.CharField(max_length=255)),
                ('structureID', models.CharField(max_length=255)),
                ('buildingPlace', models.CharField(max_length=255)),
                ('contractID', models.CharField(max_length=255)),
                ('contractDate', models.CharField(max_length=255)),
                ('departmentCode', models.CharField(max_length=255)),
                ('reName', models.CharField(max_length=255)),
                ('reLevel', models.CharField(max_length=255)),
                ('reNum', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
            ],
            bases=('api.report',),
        ),
    ]
